# Generated by Django 5.2.7 on 2025-10-27 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.CharField(default='No description', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='name',
            field=models.CharField(default='null', max_length=30),
        ),
    ]
