# Generated by Django 5.2.7 on 2025-10-23 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='users',
            fields=[
                ('name', models.CharField(max_length=25)),
                ('email', models.CharField(max_length=20)),
                ('mobile', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('document', models.FileField(upload_to='documents/')),
            ],
        ),
    ]
