# Generated by Django 5.2.7 on 2025-10-21 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='student',
            new_name='Data',
        ),
    ]
