# Generated by Django 5.2.7 on 2025-11-11 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emp_data',
            name='role',
            field=models.CharField(max_length=100),
        ),
    ]
